### PR TITLE
Bugfix/query string edge cases

### LINKED ISSUE #196: [BUG] Query string params don't work in certain cases
I found two edge-cases where the query string parameters are not working in a macro handler:
- same name as the route
```rust
#[get("/queries")]
async fn multiple_queries(&self, queries: Option<usize>) -> Result<Json<Vec<World>>, BenchmarkControllerError> {
    // GET /queries?queries=20
    println!("{:?}", queries); // None
}
```
- single-letter
```rust
#[get("/queries")]
async fn multiple_queries(&self, q: Option<usize>) -> Result<Json<Vec<World>>, BenchmarkControllerError> {
    // GET /queries?q=20
    println!("{:?}", q); // None
}
```

Other schemes works properly:
```rust
#[get("/queries")]
async fn multiple_queries(&self, nb: Option<usize>) -> Result<Json<Vec<World>>, BenchmarkControllerError> {
    // GET /queries?nb=20
    println!("{:?}", q); // Some(20)
}
```

### PR DESCRIPTION
**Pull request by Samuel-B-D**
Fixes #196

### CODE REVIEW

**Review by richerarc — APPROVED** [review]

File: saphir_macro/src/controller/handler.rs [hunk 1]
```diff
@@ -64,7 +64,7 @@ impl ArgsReprType {
                 Err(Error::new_spanned(p, "Invalid option type"))
             }
             _params => Ok(ArgsReprType::Params {
-                is_query_param: !attrs.methods_paths.iter().any(|(_, path)| path.contains(name)),
+                is_query_param: !attrs.methods_paths.iter().any(|(_, path)| path.contains(&format!("<{}>", name))),
```
Comment (Samuel-B-D) [inline saphir_macro/src/controller/handler.rs:67]: @richerarc Technically this add an un-necessary allocation, but since it's only tested at server startup and writing a non-allocating check is not as trivial and readable as this solution I think this is fine?
